sudo: required
services:
  - docker

before_install:
  - docker build -t kenjifam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kenjifam/react-test npm test -- --coverage

after_success:
  - docker build -t kenjifam/multi-client ./client
  - docker build -t kenjifam/multi-nginx ./nginx
  - docker build -t kenjifam/multi-server ./server
  - docker build -t kenjifam/multi-worker ./worker
  
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kenjifam/multi-client
  - docker push kenjifam/multi-nginx
  - docker push kenjifam/multi-server
  - docker push kenjifam/multi-worker
  